ssapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('login/new_page/', views.new_page, name='new_page'),
    path('details/', views.student_details, name='details'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),  # AJAX
    path('details/success/', views.success, name='success'),
    path('logout', views.logout, name='logout'),
]

ssproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ssapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssapp/models.py
from django.db import models


class Department(models.Model):
    department = models.CharField(max_length=50)

    def __str__(self):
        return self.department


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.CharField(max_length=50)

    def __str__(self):
        return self.course


class Details(models.Model):
    name = models.CharField(max_length=250)
    date_of_birth = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=250)
    phone_number = models.CharField(blank=True, unique=True, max_length=250)
    email = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    purpose = models.CharField(max_length=250)
    materials = models.CharField(max_length=250)

    def __str__(self):
        return self.name

ssapp/forms.py
from django import forms
from .models import Details, Course


class DateInput(forms.DateInput):
    input_type = 'date'


class DetailsForm(forms.ModelForm):
    genders = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))
    gender = forms.ChoiceField(choices=genders, widget=forms.RadioSelect)
    purposes = (('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return'))
    purpose = forms.ChoiceField(choices=purposes, widget=forms.RadioSelect)
    material = (('Debit Note Book', 'Debit Note Book'), ('Pen', 'Pen'), ('Exam Papers', 'Exam Papers'))
    materials = forms.ChoiceField(choices=material, widget=forms.RadioSelect)
    date_of_birth = forms.DateField(widget=DateInput(attrs={'onchange': "calculateAge()"}))

    class Meta:
        model = Details
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('course')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('course')

ssapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from ssapp.forms import DetailsForm
from ssapp.models import Course


# Create your views here.
def home(request):
    return render(request, 'home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('new_page/')
        else:
            messages.info(request, "Invalid Credentials")
            return redirect('login')

    return render(request, "login.html")



def register(request):
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        cpassword = request.POST.get('password1', '').strip()
        if not username or not password or not cpassword:
            messages.info(request, 'Please fill all the fields')
            return redirect('/register')
        elif password != cpassword:
            messages.info(request, 'Password does not match')
            return redirect('/register')
        elif User.objects.filter(username=username).exists():
            messages.info(request, 'Username already used')
            return redirect('/register')
        else:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return redirect('/login')
    else:
        return render(request, 'register.html')

    
def new_page(request):
    return render(request, 'new_page.html')
    
    
def logout(request):
    auth.logout(request)
    return redirect('/')


def student_details(request):
    form = DetailsForm()
    courses = Course.objects.all()
    if request.method == 'POST':
        form = DetailsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success/')
    return render(request, 'form.html', {'form': form, 'courses': courses})


def load_courses(request):
    print('..........hre we are')
    department_id = request.GET.get('department_id')
    courcess = Course.objects.filter(department_id=department_id).order_by('course')
    return render(request, 'course_dropdown_list_options.html', {'courcess': courcess})


def success(request):
    return render(request, 'success.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}ABC School{% endblock %}</title>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Custom CSS -->
    <style>
        .navbar {
            background-color: #25274d;
            color: #ffffff;
            height: 80px;
            position: static;
        }
        .navbar-brand {
            font-weight: bold;
        }
        .nav-link {
            color:  #6B6FD6;
        }
        .nav-link:hover {
            background-color: #3a3d70;
        }
        .dropdown-item.active, .dropdown-item:active {
            background-color: #6b6fd6;
        }
        .navbar-toggler{
            color: #6b6fd6;
            border-color: #6B6FD6;
            background-color: #3a3d70;
        }
        .navbar-toggler-icon {
            display: inline-block;
            width: 1.5em;
            height: 1.5em;
            vertical-align: middle;
            content: "";
            color: #6B6FD6;
            background-color: no-repeat center center;
            background-size: 100% 100%;       }

        .navbar {
            margin-bottom: 30px; /* add margin to the bottom of the navbar */
        }
        .container {
            padding-top: 30px; /* add padding to the top of the container */
            padding-bottom: 30px; /* add padding to the bottom of the container */
        }
        footer {
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #25274d;
            color: #6B6FD6;
            text-align: center;
<!--            padding: 20px;-->
        }
        .sticky-footer {
            position: sticky;
            top: 100%;
        }

        body{
            min-height: 100vh;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'img/schoologo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    ABC School
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
       {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/details">Form</a>
      </li>
       {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Departments
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Biology">Biology</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Home_science">Home Science</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">Humanities</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
        </div>
      </li>
    </ul>
  </div>
</nav>


<!-- Load Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<!-- Render content from child templates -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="sticky-footer">
  <div class="container py-3">
    <div class="row">
      <div class="col text-center">
        <p class="mb-0">&copy; 2023 ABC School. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>


</body>
</html>

templates/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courcess %}
<option value="{{ course.pk }}">{{ course.course }}</option>
{% endfor %}

templates/form.html
{% extends 'base.html' %}
{% block title %}Student Form{% endblock %}
{% block content %}


<style>

.container {
    max-width: 800px;
    margin: 0 auto;
}

label {
    font-weight: bold;
}

.btn-submit {
    background-color: #007bff;
    color: #fff;
    border-color: #007bff;
}

.btn-submit:hover {
    background-color: #0069d9;
    color: #fff;
    border-color: #0062cc;
}

</style>



<div class="container">
     <center><h3>Student Form</h3></center>
    <br>
<form method="post" id="detailsForm" class="mt-4" data-courses-url="{% url 'ajax_load_courses' %}">
    <br>
    <br>
    {% csrf_token %}
    {{ form.as_p }}
       <input type="submit" value="submit" class="btn btn-primary">
</form>
</div>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
<script>
    function calculateAge() {
      const dob = new Date(document.getElementById("id_date_of_birth").value);
      const today = new Date();
      const ageInMilliseconds = today - dob;
      const ageInYears = ageInMilliseconds / (1000 * 60 * 60 * 24 * 365.25);
      document.getElementById("id_age").value = Math.floor(ageInYears);
    }
    $("#id_department").change(function () {
        console.log('change is hre')
        const url = $("#detailsForm").attr("data-courses-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data)
                $("#id_course").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);
                */
            }
        });

    });
</script>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Welcome to ABC School</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <hr class="my-4">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Login</a>
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
        <center><h3>Login</h3></center>
    <br>
    <br>
    {% csrf_token %}
    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" class="form-control" id="id_username" name="username">
    </div>
    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" class="form-control" id="id_password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'register' %}">Register</a>
    <br>
    <center>
    {% for msg in messages %}
    <h6 style="color: red;">{{msg}}</h6>
    {% endfor %}
    </center>
  </form>
{% endblock %}

templates/new_page.html
{% extends 'base.html' %}

{% block content %}
  <center>
  <h1>Welcome to the new page</h1>
    <br>
    <a href="{% url 'details' %}" class="btn btn-primary">Show Form</a>
  </center>
  <div id="form-container" style="display:none;">
  </div>
{% endblock %}

{% block scripts %}
  <script>
    const showFormBtn = document.querySelector('#show-form-btn');
    const formContainer = document.querySelector('#form-container');

    showFormBtn.addEventListener('click', () => {
      formContainer.style.display = 'block';
    });
  </script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
        <center><h3>Register</h3></center>
    <br>
    <br>
    {% csrf_token %}
    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" class="form-control" id="id_username" name="username">
    </div>
    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" class="form-control" id="id_password" name="password">
    </div>
    <div class="form-group">
      <label for="id_password1">Confirm Password:</label>
      <input type="password" class="form-control" id="id_password1" name="password1">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <br>
    <center>
    {% for msg in messages %}
    <h6 style="color: red;">{{msg}}</h6>
    {% endfor %}
     </center>
  </form>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">Form Submitted Successfully</div>
          <div class="card-body">
            <h5 class="card-title">Thank you for submitting the form!</h5>
            <p class="card-text">Your details have been saved successfully.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
<center><a href="{% url 'home' %}" class="btn btn-primary">Go to Home Page</a></center>
{% endblock %}